#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.4.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::rust2dart::IntoIntoDart;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

use crate::ble::device::BleCharacteristic;
use crate::ble::device::BleDescriptor;
use crate::ble::device::BleService;
use crate::ble::device::CharacteristicProperties;
use crate::ble::event::BleEvent;
use crate::ble::event::MapData;
use crate::ble::scan::BleDevice;
use crate::logger::LogEntry;

// Section: wire functions

fn wire_init_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "init",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| init(),
    )
}
fn wire_scan_impl(port_: MessagePort, filter: impl Wire2Api<Vec<String>> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "scan",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || {
            let api_filter = filter.wire2api();
            move |task_callback| scan(task_callback.stream_sink::<_, Vec<BleDevice>>(), api_filter)
        },
    )
}
fn wire_events_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "events",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || move |task_callback| events(task_callback.stream_sink::<_, BleEvent>()),
    )
}
fn wire_connect_impl(port_: MessagePort, id: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "connect",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_id = id.wire2api();
            move |task_callback| connect(api_id)
        },
    )
}
fn wire_disconnect_impl(port_: MessagePort, id: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "disconnect",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_id = id.wire2api();
            move |task_callback| disconnect(api_id)
        },
    )
}
fn wire_discover_services_impl(port_: MessagePort, id: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "discover_services",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || {
            let api_id = id.wire2api();
            move |task_callback| {
                discover_services(api_id, task_callback.stream_sink::<_, Vec<BleService>>())
            }
        },
    )
}
fn wire_create_log_stream_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "create_log_stream",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || {
            move |task_callback| {
                Result::<_, ()>::Ok(create_log_stream(
                    task_callback.stream_sink::<_, LogEntry>(),
                ))
            }
        },
    )
}
fn wire_uuid__method__BleCharacteristic_impl(
    port_: MessagePort,
    that: impl Wire2Api<BleCharacteristic> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "uuid__method__BleCharacteristic",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            move |task_callback| Result::<_, ()>::Ok(BleCharacteristic::uuid(&api_that))
        },
    )
}
fn wire_service_uuid__method__BleCharacteristic_impl(
    port_: MessagePort,
    that: impl Wire2Api<BleCharacteristic> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "service_uuid__method__BleCharacteristic",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            move |task_callback| Result::<_, ()>::Ok(BleCharacteristic::service_uuid(&api_that))
        },
    )
}
fn wire_properties__method__BleCharacteristic_impl(
    port_: MessagePort,
    that: impl Wire2Api<BleCharacteristic> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, CharacteristicProperties, _>(
        WrapInfo {
            debug_name: "properties__method__BleCharacteristic",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            move |task_callback| Result::<_, ()>::Ok(BleCharacteristic::properties(&api_that))
        },
    )
}
fn wire_descriptors__method__BleCharacteristic_impl(
    port_: MessagePort,
    that: impl Wire2Api<BleCharacteristic> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, Vec<BleDescriptor>, _>(
        WrapInfo {
            debug_name: "descriptors__method__BleCharacteristic",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            move |task_callback| Result::<_, ()>::Ok(BleCharacteristic::descriptors(&api_that))
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for BleCharacteristic {
    fn into_dart(self) -> support::DartAbi {
        vec![self.characteristic.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for BleCharacteristic {}
impl rust2dart::IntoIntoDart<BleCharacteristic> for BleCharacteristic {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for BleDescriptor {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.uuid.into_into_dart().into_dart(),
            self.service_uuid.into_into_dart().into_dart(),
            self.characteristic_uuid.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for BleDescriptor {}
impl rust2dart::IntoIntoDart<BleDescriptor> for BleDescriptor {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for BleDevice {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for BleDevice {}
impl rust2dart::IntoIntoDart<BleDevice> for BleDevice {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for BleEvent {
    fn into_dart(self) -> support::DartAbi {
        match self {
            Self::DeviceDiscovered { id } => vec![0.into_dart(), id.into_into_dart().into_dart()],
            Self::DeviceUpdated { id } => vec![1.into_dart(), id.into_into_dart().into_dart()],
            Self::DeviceConnected { id } => vec![2.into_dart(), id.into_into_dart().into_dart()],
            Self::DeviceDisconnected { id } => vec![3.into_dart(), id.into_into_dart().into_dart()],
            Self::ManufacturerDataAdvertisement {
                id,
                manufacturer_data,
            } => vec![
                4.into_dart(),
                id.into_into_dart().into_dart(),
                manufacturer_data.into_into_dart().into_dart(),
            ],
            Self::ServiceDataAdvertisement { id, service_data } => vec![
                5.into_dart(),
                id.into_into_dart().into_dart(),
                service_data.into_into_dart().into_dart(),
            ],
            Self::ServicesAdvertisement { id, services } => vec![
                6.into_dart(),
                id.into_into_dart().into_dart(),
                services.into_into_dart().into_dart(),
            ],
        }
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for BleEvent {}
impl rust2dart::IntoIntoDart<BleEvent> for BleEvent {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for BleService {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.uuid.into_into_dart().into_dart(),
            self.primary.into_into_dart().into_dart(),
            self.characteristics.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for BleService {}
impl rust2dart::IntoIntoDart<BleService> for BleService {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for CharacteristicProperties {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.broadcast.into_into_dart().into_dart(),
            self.read.into_into_dart().into_dart(),
            self.write_without_response.into_into_dart().into_dart(),
            self.write.into_into_dart().into_dart(),
            self.notify.into_into_dart().into_dart(),
            self.indicate.into_into_dart().into_dart(),
            self.authenticated_signed_writes
                .into_into_dart()
                .into_dart(),
            self.extended_properties.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for CharacteristicProperties {}
impl rust2dart::IntoIntoDart<CharacteristicProperties> for CharacteristicProperties {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for LogEntry {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.time_millis.into_into_dart().into_dart(),
            self.msg.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for LogEntry {}
impl rust2dart::IntoIntoDart<LogEntry> for LogEntry {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for MapData {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.key.into_into_dart().into_dart(),
            self.data.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for MapData {}
impl rust2dart::IntoIntoDart<MapData> for MapData {
    fn into_into_dart(self) -> Self {
        self
    }
}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    use super::*;
    // Section: wire functions

    #[wasm_bindgen]
    pub fn wire_init(port_: MessagePort) {
        wire_init_impl(port_)
    }

    #[wasm_bindgen]
    pub fn wire_scan(port_: MessagePort, filter: JsValue) {
        wire_scan_impl(port_, filter)
    }

    #[wasm_bindgen]
    pub fn wire_events(port_: MessagePort) {
        wire_events_impl(port_)
    }

    #[wasm_bindgen]
    pub fn wire_connect(port_: MessagePort, id: String) {
        wire_connect_impl(port_, id)
    }

    #[wasm_bindgen]
    pub fn wire_disconnect(port_: MessagePort, id: String) {
        wire_disconnect_impl(port_, id)
    }

    #[wasm_bindgen]
    pub fn wire_discover_services(port_: MessagePort, id: String) {
        wire_discover_services_impl(port_, id)
    }

    #[wasm_bindgen]
    pub fn wire_create_log_stream(port_: MessagePort) {
        wire_create_log_stream_impl(port_)
    }

    #[wasm_bindgen]
    pub fn wire_uuid__method__BleCharacteristic(port_: MessagePort, that: JsValue) {
        wire_uuid__method__BleCharacteristic_impl(port_, that)
    }

    #[wasm_bindgen]
    pub fn wire_service_uuid__method__BleCharacteristic(port_: MessagePort, that: JsValue) {
        wire_service_uuid__method__BleCharacteristic_impl(port_, that)
    }

    #[wasm_bindgen]
    pub fn wire_properties__method__BleCharacteristic(port_: MessagePort, that: JsValue) {
        wire_properties__method__BleCharacteristic_impl(port_, that)
    }

    #[wasm_bindgen]
    pub fn wire_descriptors__method__BleCharacteristic(port_: MessagePort, that: JsValue) {
        wire_descriptors__method__BleCharacteristic_impl(port_, that)
    }

    // Section: allocate functions

    // Section: related functions

    #[wasm_bindgen]
    pub fn drop_opaque_Characteristic(ptr: *const c_void) {
        unsafe {
            Arc::<Characteristic>::decrement_strong_count(ptr as _);
        }
    }

    #[wasm_bindgen]
    pub fn share_opaque_Characteristic(ptr: *const c_void) -> *const c_void {
        unsafe {
            Arc::<Characteristic>::increment_strong_count(ptr as _);
            ptr
        }
    }

    // Section: impl Wire2Api

    impl Wire2Api<String> for String {
        fn wire2api(self) -> String {
            self
        }
    }
    impl Wire2Api<Vec<String>> for JsValue {
        fn wire2api(self) -> Vec<String> {
            self.dyn_into::<JsArray>()
                .unwrap()
                .iter()
                .map(Wire2Api::wire2api)
                .collect()
        }
    }
    impl Wire2Api<BleCharacteristic> for JsValue {
        fn wire2api(self) -> BleCharacteristic {
            let self_ = self.dyn_into::<JsArray>().unwrap();
            assert_eq!(
                self_.length(),
                1,
                "Expected 1 elements, got {}",
                self_.length()
            );
            BleCharacteristic {
                characteristic: self_.get(0).wire2api(),
            }
        }
    }

    impl Wire2Api<Vec<u8>> for Box<[u8]> {
        fn wire2api(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    // Section: impl Wire2Api for JsValue

    impl<T> Wire2Api<Option<T>> for JsValue
    where
        JsValue: Wire2Api<T>,
    {
        fn wire2api(self) -> Option<T> {
            (!self.is_null() && !self.is_undefined()).then(|| self.wire2api())
        }
    }
    impl Wire2Api<RustOpaque<Characteristic>> for JsValue {
        fn wire2api(self) -> RustOpaque<Characteristic> {
            #[cfg(target_pointer_width = "64")]
            {
                compile_error!("64-bit pointers are not supported.");
            }

            unsafe { support::opaque_from_dart((self.as_f64().unwrap() as usize) as _) }
        }
    }
    impl Wire2Api<String> for JsValue {
        fn wire2api(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl Wire2Api<u8> for JsValue {
        fn wire2api(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }
    impl Wire2Api<Vec<u8>> for JsValue {
        fn wire2api(self) -> Vec<u8> {
            self.unchecked_into::<js_sys::Uint8Array>().to_vec().into()
        }
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;

#[cfg(not(target_family = "wasm"))]
mod io {
    use super::*;
    // Section: wire functions

    #[no_mangle]
    pub extern "C" fn wire_init(port_: i64) {
        wire_init_impl(port_)
    }

    #[no_mangle]
    pub extern "C" fn wire_scan(port_: i64, filter: *mut wire_StringList) {
        wire_scan_impl(port_, filter)
    }

    #[no_mangle]
    pub extern "C" fn wire_events(port_: i64) {
        wire_events_impl(port_)
    }

    #[no_mangle]
    pub extern "C" fn wire_connect(port_: i64, id: *mut wire_uint_8_list) {
        wire_connect_impl(port_, id)
    }

    #[no_mangle]
    pub extern "C" fn wire_disconnect(port_: i64, id: *mut wire_uint_8_list) {
        wire_disconnect_impl(port_, id)
    }

    #[no_mangle]
    pub extern "C" fn wire_discover_services(port_: i64, id: *mut wire_uint_8_list) {
        wire_discover_services_impl(port_, id)
    }

    #[no_mangle]
    pub extern "C" fn wire_create_log_stream(port_: i64) {
        wire_create_log_stream_impl(port_)
    }

    #[no_mangle]
    pub extern "C" fn wire_uuid__method__BleCharacteristic(
        port_: i64,
        that: *mut wire_BleCharacteristic,
    ) {
        wire_uuid__method__BleCharacteristic_impl(port_, that)
    }

    #[no_mangle]
    pub extern "C" fn wire_service_uuid__method__BleCharacteristic(
        port_: i64,
        that: *mut wire_BleCharacteristic,
    ) {
        wire_service_uuid__method__BleCharacteristic_impl(port_, that)
    }

    #[no_mangle]
    pub extern "C" fn wire_properties__method__BleCharacteristic(
        port_: i64,
        that: *mut wire_BleCharacteristic,
    ) {
        wire_properties__method__BleCharacteristic_impl(port_, that)
    }

    #[no_mangle]
    pub extern "C" fn wire_descriptors__method__BleCharacteristic(
        port_: i64,
        that: *mut wire_BleCharacteristic,
    ) {
        wire_descriptors__method__BleCharacteristic_impl(port_, that)
    }

    // Section: allocate functions

    #[no_mangle]
    pub extern "C" fn new_Characteristic() -> wire_Characteristic {
        wire_Characteristic::new_with_null_ptr()
    }

    #[no_mangle]
    pub extern "C" fn new_StringList_0(len: i32) -> *mut wire_StringList {
        let wrap = wire_StringList {
            ptr: support::new_leak_vec_ptr(<*mut wire_uint_8_list>::new_with_null_ptr(), len),
            len,
        };
        support::new_leak_box_ptr(wrap)
    }

    #[no_mangle]
    pub extern "C" fn new_box_autoadd_ble_characteristic_0() -> *mut wire_BleCharacteristic {
        support::new_leak_box_ptr(wire_BleCharacteristic::new_with_null_ptr())
    }

    #[no_mangle]
    pub extern "C" fn new_uint_8_list_0(len: i32) -> *mut wire_uint_8_list {
        let ans = wire_uint_8_list {
            ptr: support::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        support::new_leak_box_ptr(ans)
    }

    // Section: related functions

    #[no_mangle]
    pub extern "C" fn drop_opaque_Characteristic(ptr: *const c_void) {
        unsafe {
            Arc::<Characteristic>::decrement_strong_count(ptr as _);
        }
    }

    #[no_mangle]
    pub extern "C" fn share_opaque_Characteristic(ptr: *const c_void) -> *const c_void {
        unsafe {
            Arc::<Characteristic>::increment_strong_count(ptr as _);
            ptr
        }
    }

    // Section: impl Wire2Api

    impl Wire2Api<RustOpaque<Characteristic>> for wire_Characteristic {
        fn wire2api(self) -> RustOpaque<Characteristic> {
            unsafe { support::opaque_from_dart(self.ptr as _) }
        }
    }
    impl Wire2Api<String> for *mut wire_uint_8_list {
        fn wire2api(self) -> String {
            let vec: Vec<u8> = self.wire2api();
            String::from_utf8_lossy(&vec).into_owned()
        }
    }
    impl Wire2Api<Vec<String>> for *mut wire_StringList {
        fn wire2api(self) -> Vec<String> {
            let vec = unsafe {
                let wrap = support::box_from_leak_ptr(self);
                support::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(Wire2Api::wire2api).collect()
        }
    }
    impl Wire2Api<BleCharacteristic> for wire_BleCharacteristic {
        fn wire2api(self) -> BleCharacteristic {
            BleCharacteristic {
                characteristic: self.characteristic.wire2api(),
            }
        }
    }
    impl Wire2Api<BleCharacteristic> for *mut wire_BleCharacteristic {
        fn wire2api(self) -> BleCharacteristic {
            let wrap = unsafe { support::box_from_leak_ptr(self) };
            Wire2Api::<BleCharacteristic>::wire2api(*wrap).into()
        }
    }

    impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
        fn wire2api(self) -> Vec<u8> {
            unsafe {
                let wrap = support::box_from_leak_ptr(self);
                support::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    // Section: wire structs

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_Characteristic {
        ptr: *const core::ffi::c_void,
    }

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_StringList {
        ptr: *mut *mut wire_uint_8_list,
        len: i32,
    }

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_BleCharacteristic {
        characteristic: wire_Characteristic,
    }

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_uint_8_list {
        ptr: *mut u8,
        len: i32,
    }

    // Section: impl NewWithNullPtr

    pub trait NewWithNullPtr {
        fn new_with_null_ptr() -> Self;
    }

    impl<T> NewWithNullPtr for *mut T {
        fn new_with_null_ptr() -> Self {
            std::ptr::null_mut()
        }
    }

    impl NewWithNullPtr for wire_Characteristic {
        fn new_with_null_ptr() -> Self {
            Self {
                ptr: core::ptr::null(),
            }
        }
    }

    impl NewWithNullPtr for wire_BleCharacteristic {
        fn new_with_null_ptr() -> Self {
            Self {
                characteristic: wire_Characteristic::new_with_null_ptr(),
            }
        }
    }

    impl Default for wire_BleCharacteristic {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    // Section: sync execution mode utility

    #[no_mangle]
    pub extern "C" fn free_WireSyncReturn(ptr: support::WireSyncReturn) {
        unsafe {
            let _ = support::box_from_leak_ptr(ptr);
        };
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
